version: '3.3'
services:
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_${CONTAINER_APP_NAME}
        build:
            context: docker
            dockerfile: Dockerfile
            args:
                USER: ${CONTAINER_USER_NAME}
                GROUP: ${CONTAINER_GROUP_NAME}
                UID: ${LOCAL_UID}
                GID: ${LOCAL_GID}
        ports:
            - ${FORWARDED_APP_PORT:-80}:80
        volumes:
            - ./:/var/www/app
    mysql:
        image: mysql/mysql-server:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - '3306:3306'
        expose:
            - ${DB_PORT}
volumes:
    my-db:
